package com.socialblog.follower.application;import com.socialblog.follower.api.ApiException;import com.socialblog.follower.domain.*;import com.socialblog.follower.repository.*;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service public class FollowService{public record Relationship(UUID targetId,boolean following,long followerCount,long followingCount){}public record UserLink(UUID userId,String displayName,Instant followedAt){}private final FollowRepository follows;private final UserProjectionRepository users;private final OutboxEventRepository outbox;private final DomainEventFactory events;public FollowService(FollowRepository f,UserProjectionRepository u,OutboxEventRepository o,DomainEventFactory e){follows=f;users=u;outbox=o;events=e;}@Transactional public Relationship follow(UUID actor,UUID target){if(actor.equals(target))throw new ApiException(HttpStatus.BAD_REQUEST,"SELF_FOLLOW_NOT_ALLOWED","A user cannot follow themselves");if(!users.existsByIdAndActiveTrue(target))throw new ApiException(HttpStatus.CONFLICT,"USER_NOT_AVAILABLE","Target user is unavailable");if(follows.findByFollowerIdAndFollowedId(actor,target).isEmpty()){Follow f=follows.save(new Follow(actor,target));outbox.save(events.followed(f));}return status(actor,target);}@Transactional public Relationship unfollow(UUID actor,UUID target){follows.findByFollowerIdAndFollowedId(actor,target).ifPresent(f->{follows.delete(f);outbox.save(events.unfollowed(f));});return status(actor,target);}@Transactional(readOnly=true)public Relationship status(UUID actor,UUID target){return new Relationship(target,follows.existsByFollowerIdAndFollowedId(actor,target),follows.countByFollowedId(target),follows.countByFollowerId(target));}
@Transactional(readOnly=true)public Page<UserLink>followers(UUID user,Pageable p){
    Page<Follow> page = follows.findByFollowedIdOrderByCreatedAtDesc(user,p);
    List<UUID> ids = page.stream().map(Follow::getFollowerId).toList();
    Map<UUID, String> names = users.findAllById(ids).stream().collect(java.util.stream.Collectors.toMap(UserProjection::getId, UserProjection::getDisplayName));
    return page.map(f->new UserLink(f.getFollowerId(),names.get(f.getFollowerId()),f.getCreatedAt()));
}
@Transactional(readOnly=true)public Page<UserLink>following(UUID user,Pageable p){
    Page<Follow> page = follows.findByFollowerIdOrderByCreatedAtDesc(user,p);
    List<UUID> ids = page.stream().map(Follow::getFollowedId).toList();
    Map<UUID, String> names = users.findAllById(ids).stream().collect(java.util.stream.Collectors.toMap(UserProjection::getId, UserProjection::getDisplayName));
    return page.map(f->new UserLink(f.getFollowedId(),names.get(f.getFollowedId()),f.getCreatedAt()));
}}
