package com.socialblog.comment.api;
import com.fasterxml.jackson.databind.*;import com.socialblog.comment.domain.*;import com.socialblog.comment.repository.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.MockMvc;import java.util.UUID;import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class CommentControllerIntegrationTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired ArticleProjectionRepository articles;@Autowired OutboxEventRepository outbox;
 @Test void commentReplyOwnershipSoftDeleteAndEvents()throws Exception{UUID article=UUID.randomUUID(),author=UUID.randomUUID();articles.save(new ArticleProjection(article,true));String root=mvc.perform(post("/api/v1/comments").header("X-Correlation-ID","comment-created-correlation").with(jwt().jwt(j->j.subject(author.toString()))).contentType(MediaType.APPLICATION_JSON).content("{\"articleId\":\""+article+"\",\"content\":\"Root\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();assertThat(outbox.findAll()).anySatisfy(e->assertThat(e.getPayload()).contains("CommentCreated","comment-created-correlation"));String rootId=json.readTree(root).get("id").asText();mvc.perform(post("/api/v1/comments").with(jwt().jwt(j->j.subject(author.toString()))).contentType(MediaType.APPLICATION_JSON).content("{\"articleId\":\""+article+"\",\"parentId\":\""+rootId+"\",\"content\":\"Reply\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.parentId").value(rootId));mvc.perform(put("/api/v1/comments/"+rootId).with(jwt().jwt(j->j.subject(UUID.randomUUID().toString()))).contentType(MediaType.APPLICATION_JSON).content("{\"content\":\"No\"}")).andExpect(status().isForbidden());mvc.perform(delete("/api/v1/comments/"+rootId).header("X-Correlation-ID","comment-deleted-correlation").with(jwt().jwt(j->j.subject(author.toString())))).andExpect(status().isNoContent());assertThat(outbox.findAll()).anySatisfy(e->assertThat(e.getPayload()).contains("CommentDeleted","comment-deleted-correlation"));mvc.perform(get("/api/v1/comments/articles/"+article)).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].status").value("DELETED")).andExpect(jsonPath("$.content[1].status").value("ACTIVE"));}
 @Test void rejectsCommentForUnknownArticle()throws Exception{mvc.perform(post("/api/v1/comments").with(jwt().jwt(j->j.subject(UUID.randomUUID().toString()))).contentType(MediaType.APPLICATION_JSON).content("{\"articleId\":\""+UUID.randomUUID()+"\",\"content\":\"No\"}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("ARTICLE_NOT_AVAILABLE"));}
 @Test void createRequiresAuthentication()throws Exception{mvc.perform(post("/api/v1/comments").contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isUnauthorized());}
 @Test void standardizesValidationAndPathErrors()throws Exception{UUID article=UUID.randomUUID();mvc.perform(post("/api/v1/comments").with(jwt().jwt(j->j.subject(UUID.randomUUID().toString()))).contentType(MediaType.APPLICATION_JSON).content("{\"articleId\":\""+article+"\",\"content\":\"\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_FAILED")).andExpect(jsonPath("$.fields.content").isNotEmpty());mvc.perform(get("/api/v1/comments/articles/not-a-uuid")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("INVALID_REQUEST_PARAMETER")).andExpect(jsonPath("$.fields.articleId").isNotEmpty());}
}
