package com.socialblog.notification.application;
import com.fasterxml.jackson.databind.*;import com.socialblog.notification.domain.*;import com.socialblog.notification.repository.*;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.kafka.annotation.KafkaListener;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.UUID;
@Component @ConditionalOnProperty(name="app.kafka.consumer-enabled",havingValue="true",matchIfMissing=true)
public class NotificationEventConsumer{
 private final ObjectMapper json;private final NotificationRepository notifications;private final FollowProjectionRepository follows;private final ProcessedEventRepository processed;
 public NotificationEventConsumer(ObjectMapper j,NotificationRepository n,FollowProjectionRepository f,ProcessedEventRepository p){json=j;notifications=n;follows=f;processed=p;}
 @KafkaListener(topics={"followers.events","comments.events","interactions.events","articles.events"})@Transactional
 public void consume(String raw)throws Exception{JsonNode e=json.readTree(raw);UUID event=uuid(e,"eventId");if(processed.existsById(event))return;String type=e.path("eventType").asText();UUID actor=uuid(e,"actorId");JsonNode p=e.path("payload");Instant at=e.hasNonNull("occurredAt")?Instant.parse(e.path("occurredAt").asText()):Instant.now();switch(type){case"UserFollowed"->{UUID recipient=uuid(p,"followedId");UUID follower=uuid(p,"followerId");follows.save(new FollowProjection(new FollowKey(follower,recipient)));save(event,recipient,actor,Notification.Type.NEW_FOLLOWER,"USER",follower,p.toString(),at);}case"UserUnfollowed"->follows.deleteById(new FollowKey(uuid(p,"followerId"),uuid(p,"followedId")));case"CommentCreated"->{UUID recipient=optionalUuid(p,"recipientId");Notification.Type notificationType=p.hasNonNull("parentId")?Notification.Type.NEW_REPLY:Notification.Type.NEW_COMMENT;save(event,recipient,actor,notificationType,"COMMENT",uuid(p,"commentId"),p.toString(),at);}case"InteractionCreated"->save(event,optionalUuid(p,"recipientId"),actor,Notification.Type.NEW_LIKE,p.path("targetType").asText(),uuid(p,"targetId"),p.toString(),at);case"ArticlePublished"->{UUID article=uuid(p,"articleId");for(FollowProjection f:follows.findByIdFollowedId(actor))save(event,f.getId().followerId(),actor,Notification.Type.NEW_ARTICLE,"ARTICLE",article,p.toString(),at);}default->{return;}}processed.save(new ProcessedEvent(event,type));}
 private void save(UUID event,UUID recipient,UUID actor,Notification.Type type,String entityType,UUID entity,String metadata,Instant at){if(recipient!=null&&!recipient.equals(actor))notifications.save(new Notification(event,recipient,actor,type,entityType,entity,metadata,at));}
 private UUID uuid(JsonNode n,String field){return UUID.fromString(n.path(field).asText());}private UUID optionalUuid(JsonNode n,String field){return n.hasNonNull(field)?uuid(n,field):null;}
}
