listen              1935;
max_connections     1000;
srs_log_tank        console;
daemon              off;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    1;
        hls_window      3;
        hls_dispose     10;
        hls_wait_keyframe   off;
    }
    
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    
    http_hooks {
        enabled         on;
        on_publish      http://article-service:8080/api/v1/articles/livestream/webhook/on-publish;
        on_unpublish    http://article-service:8080/api/v1/articles/livestream/webhook/on-unpublish;
    }
}

vhost localhost {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    1;
        hls_window      3;
        hls_dispose     10;
        hls_wait_keyframe   off;
    }
    
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    
    http_hooks {
        enabled         on;
        on_publish      http://article-service:8080/api/v1/articles/livestream/webhook/on-publish;
        on_unpublish    http://article-service:8080/api/v1/articles/livestream/webhook/on-unpublish;
    }
}
